[workspace]
resolver = "2"
members = [
    "aoc",
    "day00-template",
    "day01",
    "day02",
    "day03",
    "day04",
    "day06",
    "day05",
    "day07",
    "day08",
    "day09",
    "day10",
    "day11",
]

