[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
ariadne = "0.6.0"
chumsky = "0.11.2"
color-eyre = "0.6.5"
humantime = "2.3.0"
nom = "8.0.0"
nom-language = "0.1.0"
